[profile.release]
codegen-units = 1
lto = "fat"

[workspace]
members = [
    "ruhvro",
    ]

[package]
name = "pyruhvro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyruhvro"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.3"
ruhvro = {path = "ruhvro"}
apache-avro = {version = "0.16.0" }
arrow = {version = "50.0.0", features = ["pyarrow"]}

